# Generated by Django 5.1.1 on 2024-10-26 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productentry_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='wishlist_users',
            field=models.ManyToManyField(blank=True, related_name='wishlist_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
